
[
	Exposed = Window,
	NoInterfaceObject
] interface TangramWinform : EventTarget {

	// Message API
	void addChannel(DOMString channel);
	void removeChannel(DOMString channel);
	void sendMessage(DOMString id, DOMString param1, DOMString param2, DOMString param3, DOMString param4, DOMString param5);

	readonly attribute DOMString name;
	readonly attribute long formhandle;

	// Event handler attributes
	attribute EventHandler onMessageReceived;
	attribute EventHandler onTangramNodeCreated;
	attribute EventHandler onNodeMouseActivate;
	attribute EventHandler onMdiChildActivate;
	attribute EventHandler onTreeViewNodeAfterSelect;
	attribute EventHandler onTreeViewNodeMouseDoubleClick;
	attribute EventHandler onListViewItemSelectionChanged;
	attribute EventHandler onFormButtonClick;
	attribute EventHandler onFormMenuItemClick;
	attribute EventHandler onWinFormCreated;
	attribute EventHandler onWinFormClosed;
	attribute EventHandler onBindCLRCtrlEvent;
};
