typedef sequence<any> ObjectArray;

[
	Exposed = Window, 
	NoInterfaceObject 
] interface Tangram : EventTarget {

	// Internal API
	void ipcMessage__(DOMString routing, DOMString param1, DOMString param2);

	// Message API
	void addChannel(DOMString channel);
	void removeChannel(DOMString channel);
	DOMString sendMessage(DOMString to, DOMString payload, optional DOMString extra = "", optional DOMString msgId = "");

	// Event handler attributes
	attribute EventHandler onMessageReceived;

	// DOM API
	void defineElement(DOMString tagName, DOMString html);
	void renderElement(DOMString tagName, DOMString html);
};
