[
  Constructor(DOMString event_type,
  DOMString from,
  DOMString to,
  DOMString msgid,
  DOMString payload,
  DOMString extra),
  Exposed = Window
] interface TangramEvent : Event {
  attribute DOMString from;
  attribute DOMString to;
  attribute DOMString msgid;
  attribute DOMString payload;
  attribute DOMString extra;
};
