[
  Constructor(DOMString event_type,
  DOMString eventId,
  DOMString param1,
  DOMString param2,
  DOMString param3,
  DOMString param4,
  DOMString param5, 
  long handleSource, 
  long handleTarget),
  Exposed = Window
] interface TangramEvent : Event {
  attribute DOMString eventId;
  attribute DOMString param1;
  attribute DOMString param2;
  attribute DOMString param3;
  attribute DOMString param4;
  attribute DOMString param5;
  attribute long handleSource;
  attribute long handleTarget;
};
