#pragma once

using namespace ATL;

template <class T>
class CProxy_IChromForVSAppObjEvents : public IConnectionPointImpl<T, &__uuidof( _IChromForVSAppObjEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
