#pragma once

using namespace ATL;

template <class T>
class CProxy_IWebRuntimeCtrlEvents : public IConnectionPointImpl<T, &__uuidof(_IWebRuntimeCtrlEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
